title: CSCI 104
email: csci104@bytes.usc.edu
description: The homepage for CSCI 104 at USC
baseurl: "" # Path
url: "" # Protocol and host name

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-toc

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
